#!/usr/bin/env bash
# run.sh — Validate prepared audit runtime, load config, and run OMP.
# Usage: bash run.sh "audit the target repo"
#        bash run.sh                   (opens OMP interactive)
set -euo pipefail

HARNESS_ROOT="$(cd "$(dirname "$0")" && pwd)"

# Keep tool homes, caches, temp files, and agent side effects inside the
# harness repo during audit execution.
# shellcheck source=scripts/harness-lib.sh
source "${HARNESS_ROOT}/scripts/harness-lib.sh"
harness_setup_containment "$HARNESS_ROOT"

# Drop stale agent context from previous harness runs before OMP starts.
rm -f "${HARNESS_ROOT}/.harness/agent-context.json"

# Load config.toml env vars. OMP state itself is generated by bootstrap-omp.sh;
# parse-config.py stays read-only so validation cannot mutate runtime config.
eval "$("${HARNESS_ROOT}/scripts/load-config.sh")"

# Prefer bundled OMP, fall back to global install. Keep --version independent
# from audit readiness so runtime drift can be diagnosed even if the LLM is down.
OMP_BIN="${HARNESS_ROOT}/bins/omp"
if [ ! -x "${OMP_BIN}" ]; then
    OMP_BIN="$(command -v omp 2>/dev/null || true)"
fi
if [ -z "${OMP_BIN}" ]; then
    echo "[error] omp not found — run: bash scripts/install-tools.sh" >&2
    exit 1
fi
if [ "${1:-}" = "--version" ] || [ "${1:-}" = "-v" ]; then
    exec "${OMP_BIN}" "$@"
fi

# Seed harness-local OMP config/model registry so OMP starts without the setup
# wizard and without touching the operator's real home directory.
"${HARNESS_ROOT}/scripts/bootstrap-omp.sh" >/dev/null

# Audit runtime must be fully prepared before OMP starts. Bootstrap commands
# such as install-tools.sh, fetch-osv-db.sh, dependency setup, and clone-target.sh
# stay outside this path.
"${HARNESS_ROOT}/scripts/validate-config.sh" >/dev/null

# Tool allowlist is the single source of truth for the OMP session tool set
# (operator preference: only real OMP tool names, single-sourced here).
# search_tool_bm25 is intentionally NOT in --tools: the harness binds its tool set
# explicitly and --tools allowlisting disables MCP discovery. To enable BM25 tool
# discovery, add the tool here and remove this comment (Step 10 of the consistency plan).
"${OMP_BIN}" \
    --append-system-prompt "${HARNESS_ROOT}/.omp/main/vulnops-main.md" \
    --tools "read,bash,edit,write,grep,glob,lsp,task,todo,irc,ask" \
    --approval-mode yolo \
    --advisor \
    "$@"
