#!/usr/bin/env bash
# Seed harness-local OMP state from config.toml without interactive setup.

set -euo pipefail

HARNESS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# shellcheck source=scripts/harness-lib.sh
source "${HARNESS_ROOT}/scripts/harness-lib.sh"
harness_setup_containment "$HARNESS_ROOT"

PYTHON="$(command -v python3 2>/dev/null || true)"

if [ -z "$PYTHON" ]; then
    echo "[bootstrap-omp] python3 not found" >&2
    exit 1
fi

"$PYTHON" - "$HARNESS_ROOT" <<'PY'
from __future__ import annotations

import os
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:
    print("[bootstrap-omp] Python 3.11+ tomllib is required", file=sys.stderr)
    raise SystemExit(1)


def q(value: object) -> str:
    text = "" if value is None else str(value)
    return "'" + text.replace("'", "''") + "'"


def normalize_auth(value: object) -> str:
    raw = str(value or "api-key").strip().lower().replace("_", "-")
    if raw in {"none", "no-auth", "noauth", "anonymous"}:
        return "none"
    return "apiKey"


def as_int(value: object, default: int) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def as_optional_int(value: object) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == content:
        return
    path.write_text(content)


root = Path(sys.argv[1]).resolve()
config_path = root / "config.toml"
if not config_path.exists():
    print(f"[bootstrap-omp] missing config.toml: {config_path}", file=sys.stderr)
    raise SystemExit(1)

with config_path.open("rb") as handle:
    cfg = tomllib.load(handle)

llm = cfg.get("llm", {})
provider = llm.get("provider", {})

provider_name = str(provider.get("name") or "on-prem")
base_url = str(llm.get("base_url") or "").rstrip("/")
api_key = str(llm.get("api_key") or "")
model_id = str(llm.get("model") or "")
api = str(provider.get("api") or "openai-completions")
auth = normalize_auth(provider.get("auth", "api-key"))

if not base_url:
    print("[bootstrap-omp] llm.base_url is empty", file=sys.stderr)
    raise SystemExit(1)
if not model_id:
    print("[bootstrap-omp] llm.model is empty", file=sys.stderr)
    raise SystemExit(1)

selector = f"{provider_name}/{model_id}"
agent_dir = Path(os.environ.get("PI_CODING_AGENT_DIR") or root / ".harness/home/.omp/agent")

disabled_providers = [
    "anthropic",
    "openai",
    "google",
    "groq",
    "openrouter",
    "mistral",
    "xai",
    "xai-oauth",
    "github-copilot",
    "cursor",
    "cerebras",
    "deepseek",
    "fireworks",
    "together",
    "nvidia",
    "huggingface",
    "moonshot",
    "kimi-code",
    "nanogpt",
    "venice",
    "vercel-ai-gateway",
    "cloudflare-ai-gateway",
    "litellm",
    "kilo",
    "zai",
    "zenmux",
    "zhipu-coding-plan",
    "qianfan",
    "qwen-portal",
    "synthetic",
    "minimax",
    "alibaba-coding-plan",
    "aimlapi",
    "gitlab-duo",
    "opencode-zen",
    "opencode-go",
    "firepass",
    "wafer-pass",
    "wafer-serverless",
    "xiaomi",
    "ollama-cloud",
    "ollama",
    "llama.cpp",
    "lm-studio",
    "azure-openai-responses",
    "amazon-bedrock",
    "google-vertex",
]
disabled_providers = [name for name in disabled_providers if name != provider_name]

config_lines = [
    "# Auto-generated by scripts/bootstrap-omp.sh. Do not edit.",
    "# Source of truth: config.toml.",
    "",
    "setupVersion: 1",
    "startup:",
    "  setupWizard: false",
    "",
    "modelProviderOrder:",
    f"  - {q(provider_name)}",
    "enabledModels:",
    f"  - {q(selector)}",
    "modelRoles:",
    f"  default: {q(selector)}",
    f"  task: {q(selector)}",
    f"  slow: {q(selector)}",
    f"  smol: {q(selector)}",
    f"  plan: {q(selector)}",
    "",
    "disabledProviders:",
]
config_lines.extend(f"  - {q(name)}" for name in disabled_providers)
config_lines.extend(
    [
        "",
        "memory:",
        "  enabled: false",
        "autolearn:",
        "  enabled: false",
        "web_search:",
        "  enabled: false",
        "browser:",
        "  enabled: false",
        "search:",
        "  enabled: false",
        "remote:",
        "  enabled: false",
        "",
    ]
)

models = provider.get("models") or []
model_record = None
for item in models:
    if str(item.get("id") or "") == model_id:
        model_record = item
        break
if model_record is None:
    model_record = {}

model_name = str(model_record.get("name") or model_id.split("/")[-1])
context_window = as_optional_int(model_record.get("contextWindow", model_record.get("context_window")))
max_tokens = as_optional_int(model_record.get("maxTokens", model_record.get("max_tokens")))

models_lines = [
    "# Auto-generated by scripts/bootstrap-omp.sh. Do not edit.",
    "# Source of truth: config.toml.",
    "",
    "providers:",
    f"  {provider_name}:",
    f"    baseUrl: {q(base_url)}",
    f"    api: {q(api)}",
    f"    auth: {q(auth)}",
]
if auth != "none":
    models_lines.append(f"    apiKey: {q(api_key)}")
models_lines.extend(
    [
        "    models:",
        f"      - id: {q(model_id)}",
        f"        name: {q(model_name)}",
# harness does not enforce context-window / max-token caps; emit only when
# explicitly pinned under [[llm.provider.models]] in config.toml. Letting the
# endpoint's own model envelope govern avoids stale defaults that constrain the
# on-prem model behind a smaller window than the endpoint actually serves.
    ]
)
if context_window is not None:
    models_lines.append(f"        contextWindow: {context_window}")
if max_tokens is not None:
    models_lines.append(f"        maxTokens: {max_tokens}")
models_lines.append("")

write_if_changed(agent_dir / "config.yml", "\n".join(config_lines))
write_if_changed(agent_dir / "models.yml", "\n".join(models_lines))
PY
