#!/usr/bin/env bash
# Shared harness runtime helpers. Keep this file dependency-free: audit startup
# uses it before agents or language-specific tooling are available.

set -euo pipefail

harness_root() {
    cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd
}

harness_setup_containment() {
    local root="${1:-$(harness_root)}"
    local hdir="${root}/.harness"

    mkdir -p \
        "${hdir}/tmp" \
        "${hdir}/cache" \
        "${hdir}/home" \
        "${hdir}/home/.omp/agent" \
        "${hdir}/home/.omp/config" \
        "${hdir}/logs" \
        "${root}/work" \
        "${root}/scans" \
        "${root}/remediations" \
        "${root}/context"

    export VULNOPSV3_ROOT="${root}"
    export VULNOPSV3_SCANS="${root}/scans"
    export VULNOPSV3_REMEDIATIONS="${root}/remediations"
    export VULNOPSV3_TARGET="${root}/target"
    export VULNOPSV3_WORK="${root}/work"
    export VULNOPSV3_HOME="${hdir}/home"

    export TMPDIR="${hdir}/tmp"
    export TMP="${hdir}/tmp"
    export TEMP="${hdir}/tmp"
    export XDG_CACHE_HOME="${hdir}/cache"
    export XDG_CONFIG_HOME="${hdir}/config"
    export XDG_DATA_HOME="${hdir}/data"
    export PIP_CACHE_DIR="${hdir}/cache/pip"
    export NPM_CONFIG_CACHE="${hdir}/cache/npm"
    export CARGO_HOME="${hdir}/cache/cargo"
    export GOMODCACHE="${hdir}/cache/go/pkg/mod"
    export GOCACHE="${hdir}/cache/go-build"
    export OMP_AGENT_HOME="${hdir}/home/.omp/agent"
    export PI_CODING_AGENT_DIR="${hdir}/home/.omp/agent"
    export PI_CONFIG_DIR="${hdir}/home/.omp"
    # codegraph runs offline-only; never phone home, never spawn a daemon
    export CODEGRAPH_TELEMETRY=0
    export CODEGRAPH_NO_DAEMON=1

    mkdir -p \
        "${XDG_CONFIG_HOME}" \
        "${XDG_DATA_HOME}" \
        "${PIP_CACHE_DIR}" \
        "${NPM_CONFIG_CACHE}" \
        "${CARGO_HOME}" \
        "${GOMODCACHE}" \
        "${GOCACHE}"

    # HOME is intentionally harness-local so agent/tool side effects do not
    # spill into the operator's user profile.
    export HOME="${VULNOPSV3_HOME}"
    export PATH="${root}/bins:${PATH}"
}

harness_resolve_for_check() {
    local path="$1"
    local depth="${2:-0}"
    local probe
    local suffix=""

    # Output paths are generated by the harness and never need parent traversal.
    # Reject it before looking for an existing ancestor: preserving an unresolved
    # `missing/..` suffix lexically can make an escaping path appear allowlisted.
    case "/${path}/" in
        *"/../"*)
            echo "[harness] path contains a forbidden parent component: ${path}" >&2
            return 1
            ;;
    esac
    if [ "$depth" -ge 40 ]; then
        echo "[harness] too many symbolic-link resolutions: ${path}" >&2
        return 1
    fi

    case "$path" in
        /*) probe="$path" ;;
        *) probe="${PWD}/${path}" ;;
    esac

    # A dangling symlink is still an existing filesystem object for the purpose
    # of containment. Stop on -L as well as -e so it cannot be mistaken for a
    # harmless missing suffix.
    while [ ! -e "$probe" ] && [ ! -L "$probe" ]; do
        local component
        component="$(basename "$probe")"
        if [ "$component" != "." ]; then
            suffix="/${component}${suffix}"
        fi
        local parent
        parent="$(dirname "$probe")"
        if [ "$parent" = "$probe" ]; then
            return 1
        fi
        probe="$parent"
    done

    # pwd -P resolves directory symlinks. Resolve a final file symlink explicitly
    # as well; allowed-output checks reject final symlinks before reaching here,
    # while read-side containment checks still need their true destination.
    if [ -L "$probe" ]; then
        local link_target
        link_target="$(readlink "$probe")" || return 1
        case "$link_target" in
            /*) probe="$link_target" ;;
            *) probe="$(dirname "$probe")/${link_target}" ;;
        esac
        local resolved_link
        resolved_link="$(harness_resolve_for_check "$probe" "$((depth + 1))")" || return 1
        printf '%s%s\n' "$resolved_link" "$suffix"
    elif [ -d "$probe" ]; then
        printf '%s%s\n' "$(cd "$probe" && pwd -P)" "$suffix"
    else
        printf '%s%s\n' "$(cd "$(dirname "$probe")" && pwd -P)/$(basename "$probe")" "$suffix"
    fi
}

harness_path_is_inside_root() {
    local root="$1"
    local path="$2"
    local resolved_root
    local resolved_path

    resolved_root="$(cd "$root" && pwd -P)" || return 1
    resolved_path="$(harness_resolve_for_check "$path")" || return 1

    case "$resolved_path" in
        "$resolved_root"|"$resolved_root"/*) return 0 ;;
        *) return 1 ;;
    esac
}

harness_require_inside_root() {
    local root="$1"
    local path="$2"
    local label="${3:-path}"

    if ! harness_path_is_inside_root "$root" "$path"; then
        echo "[harness] ${label} escapes harness root: ${path}" >&2
        return 1
    fi
}

harness_require_allowed_output() {
    local root="$1"
    local path="$2"
    local resolved
    local final_path="$path"

    # test -L follows a trailing slash on some shells. Remove every trailing
    # slash (except the filesystem root) so a directory symlink cannot bypass
    # the final-component check as `link/` or `link//`.
    while [ "$final_path" != "/" ] && [ "${final_path%/}" != "$final_path" ]; do
        final_path="${final_path%/}"
    done

    # Never write through a caller-supplied final symlink, even when its current
    # destination is another allowlisted directory. This avoids clobbering an
    # existing file through an alias and closes the final-component gap.
    if [ -L "$final_path" ]; then
        echo "[harness] output path must not be a symbolic link: ${path}" >&2
        return 1
    fi

    harness_require_inside_root "$root" "$path" "output path" || return 1
    resolved="$(harness_resolve_for_check "$path")" || return 1

    local resolved_root
    resolved_root="$(cd "$root" && pwd -P)" || return 1

    case "$resolved" in
        "$resolved_root/scans"|"$resolved_root/scans"/*|\
        "$resolved_root/remediations"|"$resolved_root/remediations"/*|\
        "$resolved_root/.harness"|"$resolved_root/.harness"/*|\
        "$resolved_root/work"|"$resolved_root/work"/*|\
        "$resolved_root/bins"|"$resolved_root/bins"/*)
            return 0
            ;;
        *)
            echo "[harness] output path is not an approved harness output area: ${path}" >&2
            return 1
            ;;
    esac
}
