#!/usr/bin/env bash
# Install the exact platform assets declared by the strict offline tool lock.
set -euo pipefail

HARNESS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTALL_DIR="${HARNESS_ROOT}/bins"
PACKAGE_TOOL="${HARNESS_ROOT}/scripts/offline_package.py"

log() { echo "[install] $*"; }
die() { echo "[install] ERROR: $*" >&2; exit 1; }

detect_platform() {
    local os_name machine
    os_name="$(uname -s | tr '[:upper:]' '[:lower:]')"
    machine="$(uname -m)"
    case "$os_name" in
        linux|darwin) ;;
        *) die "unsupported operating system: $os_name" ;;
    esac
    case "$machine" in
        x86_64|amd64) machine="amd64" ;;
        aarch64|arm64) machine="arm64" ;;
        *) die "unsupported architecture: $machine" ;;
    esac
    printf '%s_%s\n' "$os_name" "$machine"
}

usage() {
    echo "Usage: $0 [--lock PATH] [all|wraith|poltergeist|omp|osv-scanner|codegraph ...]"
}

LOCK_FILE=""
tools=()
while [ "$#" -gt 0 ]; do
    case "$1" in
        --lock)
            [ "$#" -ge 2 ] || die "--lock requires a path"
            LOCK_FILE="$2"
            shift 2
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        all|wraith|poltergeist|omp|osv-scanner|codegraph)
            tools+=("$1")
            shift
            ;;
        *)
            die "unknown argument: $1"
            ;;
    esac
done

platform="$(detect_platform)"
if [ -z "$LOCK_FILE" ]; then
    LOCK_FILE="${HARNESS_ROOT}/config/offline-pack.${platform}.lock.json"
fi
[ -f "$LOCK_FILE" ] || die "missing platform tool lock: $LOCK_FILE"
python3 "$PACKAGE_TOOL" validate-tool-lock "$LOCK_FILE" --platform "$platform"

if [ "${#tools[@]}" -eq 0 ] || [[ " ${tools[*]} " == *" all "* ]]; then
    tools=(wraith poltergeist omp osv-scanner codegraph)
fi

field() {
    python3 "$PACKAGE_TOOL" tool-field "$LOCK_FILE" "$1" "$2"
}

runtime_field() {
    python3 "$PACKAGE_TOOL" runtime-field "$LOCK_FILE" "$1" "$2"
}

fix_binary() {
    local path="$1"
    chmod +x "$path"
    if command -v xattr >/dev/null 2>&1; then
        xattr -d com.apple.quarantine "$path" 2>/dev/null || true
        xattr -d com.apple.provenance "$path" 2>/dev/null || true
    fi
}

install_regular_tool() {
    local name="$1" asset="$2" format="$3" extracted
    if [ "$format" = "binary" ]; then
        cp "$asset" "${INSTALL_DIR}/${name}"
    else
        extracted="$(mktemp -d "${INSTALL_DIR}/.${name}.extract.XXXXXX")"
        python3 "$PACKAGE_TOOL" extract-tool "$asset" "$extracted"
        local candidate
        candidate="$(find "$extracted" -type f -name "$name" -print -quit)"
        [ -n "$candidate" ] || die "verified ${name} archive did not contain the locked binary name"
        cp "$candidate" "${INSTALL_DIR}/${name}"
        rm -rf "$extracted"
    fi
    fix_binary "${INSTALL_DIR}/${name}"
}

install_codegraph() {
    local asset="$1"
    local next_bundle
    next_bundle="$(mktemp -d "${INSTALL_DIR}/.codegraph-bundle.XXXXXX")"
    python3 "$PACKAGE_TOOL" extract-tool "$asset" "$next_bundle" --strip-top-level
    [ -x "${next_bundle}/bin/codegraph" ] || die "verified codegraph bundle is missing bin/codegraph"
    if [ -d "${INSTALL_DIR}/codegraph-bundle" ]; then
        rm -rf "${INSTALL_DIR}/codegraph-bundle"
    fi
    mv "$next_bundle" "${INSTALL_DIR}/codegraph-bundle"
    printf '%s\n' \
        '#!/usr/bin/env bash' \
        '# Relocatable harness shim generated by scripts/install-tools.sh.' \
        'set -euo pipefail' \
        'BIN_DIR="$(cd "$(dirname "$0")" && pwd)"' \
        'export CODEGRAPH_NO_DOWNLOAD=1' \
        'exec "${BIN_DIR}/codegraph-bundle/bin/codegraph" "$@"' \
        >"${INSTALL_DIR}/codegraph"
    fix_binary "${INSTALL_DIR}/codegraph"
}

install_omp_runtime() {
    local name="omp-natives" temporary asset
    local version url expected_sha expected_size
    version="$(runtime_field "$name" version)"
    url="$(runtime_field "$name" url)"
    expected_sha="$(runtime_field "$name" sha256)"
    expected_size="$(runtime_field "$name" size)"
    temporary="$(mktemp -d "${INSTALL_DIR}/.${name}.download.XXXXXX")"
    asset="${temporary}/asset"
    log "${name}: downloading locked ${version}"
    if ! curl -fsSL --retry 3 --retry-all-errors -o "$asset" "$url"; then
        rm -rf "$temporary"
        die "failed to download locked ${name} asset"
    fi
    python3 "$PACKAGE_TOOL" verify-asset "$asset" "$expected_size" "$expected_sha" \
        || { rm -rf "$temporary"; die "locked ${name} asset failed verification"; }
    find "$INSTALL_DIR" -maxdepth 1 -type f -name 'pi_natives.*.node' -delete
    python3 "$PACKAGE_TOOL" install-runtime-asset "$asset" "$LOCK_FILE" "$name" "$INSTALL_DIR" \
        || { rm -rf "$temporary"; die "locked ${name} members failed verification"; }
    printf '%s\n' "$version" >"${INSTALL_DIR}/.${name}.version"
    rm -rf "$temporary"
    log "${name}: installed ${version}"
}

mkdir -p "$INSTALL_DIR"
for name in "${tools[@]}"; do
    version="$(field "$name" version)"
    url="$(field "$name" url)"
    expected_sha="$(field "$name" sha256)"
    expected_size="$(field "$name" size)"
    format="$(field "$name" format)"
    marker="${INSTALL_DIR}/.${name}.version"

    temporary="$(mktemp -d "${INSTALL_DIR}/.${name}.download.XXXXXX")"
    asset="${temporary}/asset"
    log "${name}: downloading locked ${version}"
    if ! curl -fsSL --retry 3 --retry-all-errors -o "$asset" "$url"; then
        rm -rf "$temporary"
        die "failed to download locked ${name} asset"
    fi
    python3 "$PACKAGE_TOOL" verify-asset "$asset" "$expected_size" "$expected_sha" \
        || { rm -rf "$temporary"; die "locked ${name} asset failed verification"; }

    if [ "$name" = "codegraph" ]; then
        install_codegraph "$asset"
    else
        install_regular_tool "$name" "$asset" "$format"
    fi
    if [ "$name" = "omp" ]; then
        install_omp_runtime
    fi
    printf '%s\n' "$version" >"$marker"
    rm -rf "$temporary"
    log "${name}: installed ${version}"
done

log "installation complete: ${INSTALL_DIR}"
