#!/usr/bin/env python3
"""parse-config.py — Read config.toml and emit shell export lines.

Usage:
    python3 scripts/parse-config.py [HARNESS_ROOT]

If HARNESS_ROOT is omitted, defaults to the script's parent-of-parent directory.
Output is one `export KEY=VALUE` line per variable, suitable for shell eval.
No config.toml = no output (silent exit 0).
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import tomllib  # Python 3.11+ stdlib
except ModuleNotFoundError:
    # Python < 3.11 fallback — shouldn't happen on the target venv, but
    # fail gracefully rather than crashing.
    sys.exit(0)


def _find_root(argv: list[str]) -> Path:
    if len(argv) > 1:
        return Path(argv[1]).resolve()
    return Path(__file__).resolve().parent.parent


def _dquote(val: str) -> str:
    """Escape double-quote characters inside a shell double-quoted string."""
    return val.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    root = _find_root(sys.argv)
    config_path = root / "config.toml"
    if not config_path.exists():
        return

    with open(config_path, "rb") as f:
        cfg = tomllib.load(f)

    llm = cfg.get("llm", {})
    graphify = cfg.get("graphify", {})

    # ── Core LLM vars ─────────────────────────────────────────────────
    base_url = llm.get("base_url", "")
    api_key = llm.get("api_key", "")
    model = llm.get("model", "")

    exports: list[tuple[str, str]] = [
        ("ON_PREM_LLM_BASE_URL", base_url),
        ("ON_PREM_API_KEY", api_key),
        ("ON_PREM_MODEL_NAME", model),
    ]

    # ── Graphify / Ollama derived vars ────────────────────────────────
    g_backend = graphify.get("backend", "")
    g_model = graphify.get("model", "")
    g_api_key = graphify.get("api_key", "")

    if g_backend:
        exports.append(("GRAPHIFY_BACKEND", g_backend))

    if g_backend == "ollama":
        exports.append(("OLLAMA_BASE_URL", base_url))
        exports.append(("OLLAMA_API_KEY", "local"))
        exports.append(("OLLAMA_MODEL", g_model if g_model else model))

    if g_model:
        exports.append(("GRAPHIFY_MODEL", g_model))

    if g_api_key:
        exports.append(("GRAPHIFY_API_KEY", g_api_key))

    # ── Emit ──────────────────────────────────────────────────────────
    for key, val in exports:
        print(f'export {key}="{_dquote(val)}"')

    # ── Generate models.yml for OMP ───────────────────────────────────
    # OMP does NOT resolve env var references in models.yml, so we must
    # write the actual values. This generates ~/.omp/agent/models.yml.
    provider = llm.get("provider", {})
    omp_agent = Path.home() / ".omp" / "agent"
    models_dst = omp_agent / "models.yml"
    if omp_agent.is_dir():
        models_content = _build_models_yml(base_url, api_key, model, provider)
        if models_dst.exists() and models_dst.read_text() == models_content:
            pass  # already up to date
        else:
            models_dst.write_text(models_content)


def _build_models_yml(
    base_url: str, api_key: str, model: str, provider: dict
) -> str:
    """Build models.yml content with resolved values."""
    p_name = provider.get("name", "on-prem")
    p_api = provider.get("api", "openai-completions")
    p_auth = "apiKey" if provider.get("auth", "none") != "none" else "none"
    # Strip trailing /v1 if present — OMP appends paths to baseUrl
    url = base_url.rstrip("/")

    lines = [
        "# Auto-generated by parse-config.py — DO NOT EDIT",
        "# Source of truth: config.toml [llm] section",
        "",
        "providers:",
        f"  {p_name}:",
        f"    baseUrl: {url}",
        f"    apiKey: {api_key}",
        f"    api: {p_api}",
        f"    auth: {p_auth}",
        "",
        "    models:",
        f"      - id: {model}",
        f"        name: {model.split('/')[-1]}",
        "        contextWindow: 32768",
        "        maxTokens: 8192",
        "",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    main()
