#!/usr/bin/env bash
# run-graphify.sh — Build code knowledge graph using graphify.
# Handles: config sourcing, provider setup, and fail-closed LLM extraction.
#
# Usage:
#   bash scripts/run-graphify.sh <repo_path> <output_dir> <scope_json>
#   GRAPHIFY_FULL_REPO=1 bash scripts/run-graphify.sh <repo_path> <output_dir>
#
# Output: graph.json in <output_dir>/graphify-out/
set -euo pipefail

HARNESS_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source=scripts/harness-lib.sh
source "${HARNESS_ROOT}/scripts/harness-lib.sh"
harness_setup_containment "$HARNESS_ROOT"

if [ $# -lt 2 ] || [ $# -gt 3 ]; then
    echo "Usage: $0 <repo_path> <output_dir> [scope_json]" >&2
    exit 1
fi

REPO_PATH="$1"
OUTPUT_DIR="$2"
SCOPE_FILE="${3:-}"
harness_require_inside_root "$HARNESS_ROOT" "$REPO_PATH" "repo path"
harness_require_allowed_output "$HARNESS_ROOT" "$OUTPUT_DIR"
if [ -n "$SCOPE_FILE" ]; then
    harness_require_inside_root "$HARNESS_ROOT" "$SCOPE_FILE" "scope file"
fi

# Source centralized config if Graphify vars are not already set.
if [ -z "${GRAPHIFY_BACKEND:-}" ]; then
    if [ -f "${HARNESS_ROOT}/config.toml" ] && [ -x "${HARNESS_ROOT}/scripts/load-config.sh" ]; then
        eval "$("${HARNESS_ROOT}/scripts/load-config.sh")"
    fi
fi

# Find graphify
GRAPHIFY_CLI=""
if [ -x "${HARNESS_ROOT}/.venv/bin/graphify" ]; then
    GRAPHIFY_CLI="${HARNESS_ROOT}/.venv/bin/graphify"
elif command -v graphify &>/dev/null; then
    GRAPHIFY_CLI="$(command -v graphify)"
fi

if [ -z "${GRAPHIFY_CLI}" ]; then
    echo '{"error":"graphify not installed","hint":"run: bash scripts/install-tools.sh"}' >&2
    exit 1
fi

mkdir -p "${OUTPUT_DIR}"

if [ -z "${GRAPHIFY_BACKEND:-}" ]; then
    echo "[graphify] GRAPHIFY_BACKEND is empty; run scripts/load-config.sh first" >&2
    exit 1
fi
if [ -z "${GRAPHIFY_MODEL:-}" ]; then
    echo "[graphify] GRAPHIFY_MODEL is empty; set llm.model or graphify.model" >&2
    exit 1
fi
if [ -z "$SCOPE_FILE" ] && [ "${GRAPHIFY_FULL_REPO:-0}" != "1" ]; then
    echo "[graphify] refusing whole-repo extraction because graphify.full_repo is false" >&2
    echo "[graphify] pass a scope JSON generated by scripts/build-intelligence.py or scripts/build-intrusion-plan.py, or set graphify.full_repo=true" >&2
    exit 1
fi

if [ "${GRAPHIFY_GENERATED_PROVIDER:-0}" = "1" ]; then
    if [ -z "${GRAPHIFY_BASE_URL:-}" ]; then
        echo "[graphify] GRAPHIFY_BASE_URL is empty; set llm.base_url or graphify.base_url" >&2
        exit 1
    fi
    if [ -z "${VULNOPS_GRAPHIFY_API_KEY:-}" ]; then
        echo "[graphify] VULNOPS_GRAPHIFY_API_KEY is empty; set llm.api_key or graphify.api_key" >&2
        exit 1
    fi

    provider_dir="${HOME}/.graphify"
    provider_path="${provider_dir}/providers.json"
    mkdir -p "$provider_dir"
    "${HARNESS_ROOT}/.venv/bin/python" - "$provider_path" <<'PY'
import json
import os
import sys
from pathlib import Path

path = Path(sys.argv[1])
name = os.environ["GRAPHIFY_BACKEND"]
data = {}
if path.exists():
    try:
        existing = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(existing, dict):
            data = existing
    except Exception:
        data = {}
data[name] = {
    "base_url": os.environ["GRAPHIFY_BASE_URL"],
    "default_model": os.environ["GRAPHIFY_MODEL"],
    "env_key": "VULNOPS_GRAPHIFY_API_KEY",
    "pricing": {"input": 0.0, "output": 0.0},
}
path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
PY
fi

log_slug="$(basename "$(dirname "$OUTPUT_DIR")")-$(basename "$OUTPUT_DIR")"
log_path="${HARNESS_ROOT}/.harness/logs/graphify-${log_slug}.log"
raw_log="${TMPDIR}/graphify-${log_slug}.raw.log"
mkdir -p "$(dirname "$log_path")" "$TMPDIR"

EXTRACT_PATH="$REPO_PATH"
if [ -n "$SCOPE_FILE" ]; then
    scope_tmp_root="${GRAPHIFY_SCOPE_TMP_ROOT:-/private/tmp}"
    EXTRACT_PATH="${scope_tmp_root}/vulnopsv3-graphify-scope-src-${log_slug}"
    "${HARNESS_ROOT}/.venv/bin/python" - "$REPO_PATH" "$SCOPE_FILE" "$EXTRACT_PATH" "$OUTPUT_DIR" <<'PY'
import json
import shutil
import sys
from pathlib import Path

repo = Path(sys.argv[1]).resolve()
scope_path = Path(sys.argv[2]).resolve()
dest = Path(sys.argv[3]).resolve()
out_dir = Path(sys.argv[4]).resolve()
scope = json.loads(scope_path.read_text(encoding="utf-8"))
files = scope.get("files", [])
if not isinstance(files, list) or not files:
    raise SystemExit("scope file has no files")
if dest.exists():
    shutil.rmtree(dest)
dest.mkdir(parents=True)
graphify_out = out_dir / "graphify-out"
if graphify_out.exists():
    shutil.rmtree(graphify_out)
copied = []
for raw in files:
    if not isinstance(raw, str) or raw.startswith(("/", "..")):
        continue
    src = (repo / raw).resolve()
    try:
        src.relative_to(repo)
    except ValueError:
        continue
    if not src.is_file():
        continue
    out = dest / raw
    out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, out)
    copied.append(raw)
if not copied:
    raise SystemExit("scope files did not match readable target files")
(dest / ".graphify-scope.json").write_text(json.dumps({"scope": scope, "copied_files": copied}, indent=2) + "\n", encoding="utf-8")
(dest / "VULNOPS_GRAPHIFY_SCOPE.md").write_text(
    "# VulnOps Graphify Scope\n\n"
    f"Scope ID: {scope.get('id')}\n\n"
    f"Reason: {scope.get('reason')}\n\n"
    "Seed IDs: " + ", ".join(map(str, scope.get("seed_ids", []))) + "\n\n"
    "Question types: " + ", ".join(map(str, scope.get("question_types", []))) + "\n\n"
    "Questions:\n"
    + "\n".join(
        f"- {cmd.get('question')}"
        for cmd in scope.get("commands", [])
        if isinstance(cmd, dict) and cmd.get("type") == "query" and cmd.get("question")
    )
    + "\n\nFiles in scope:\n"
    + "\n".join(f"- {item}" for item in copied)
    + "\n",
    encoding="utf-8",
)
PY
fi

cmd=("${GRAPHIFY_CLI}" extract "${EXTRACT_PATH}" --backend "${GRAPHIFY_BACKEND}" --model "${GRAPHIFY_MODEL}" --out "${OUTPUT_DIR}")
if [ -n "$SCOPE_FILE" ]; then
    cmd+=(--mode deep)
fi

set +e
"${cmd[@]}" >"$raw_log" 2>&1
status=$?
set -e

"${HARNESS_ROOT}/.venv/bin/python" - "$raw_log" "$log_path" <<'PY'
import os
import sys
from pathlib import Path

raw = Path(sys.argv[1])
dest = Path(sys.argv[2])
text = raw.read_text(encoding="utf-8", errors="replace") if raw.exists() else ""
for key in ("VULNOPS_GRAPHIFY_API_KEY", "ON_PREM_API_KEY", "OPENAI_API_KEY", "OLLAMA_API_KEY"):
    value = os.environ.get(key, "")
    if value:
        text = text.replace(value, "<redacted>")
dest.write_text(text, encoding="utf-8")
try:
    raw.unlink()
except FileNotFoundError:
    pass
PY

if [ "$status" -ne 0 ]; then
    echo "[graphify] LLM-backed extraction failed; see sanitized log: ${log_path}" >&2
    exit "$status"
fi

graph_path="${OUTPUT_DIR}/graphify-out/graph.json"
if [ ! -s "$graph_path" ]; then
    echo "[graphify] extraction completed but graph is missing or empty: ${graph_path}" >&2
    echo "[graphify] see sanitized log: ${log_path}" >&2
    exit 1
fi

validate_graph() {
    "${HARNESS_ROOT}/.venv/bin/python" - "$graph_path" "$SCOPE_FILE" <<'PY'
import json
import sys
from pathlib import Path

graph_path = Path(sys.argv[1])
scope_path = Path(sys.argv[2]) if len(sys.argv) > 2 and sys.argv[2] else None
graph = json.loads(graph_path.read_text(encoding="utf-8"))
nodes = graph.get("nodes", [])
edges = graph.get("links", graph.get("edges", []))
scope = {}
if scope_path and scope_path.is_file():
    scope = json.loads(scope_path.read_text(encoding="utf-8"))
commands = scope.get("commands", []) if isinstance(scope, dict) else []
question_types = set(scope.get("question_types", [])) if isinstance(scope, dict) else set()
requires_edges = any(isinstance(cmd, dict) and cmd.get("type") in {"query", "path", "affected"} for cmd in commands)
requires_cluster = bool(scope.get("requires_cluster")) or "cross_boundary" in question_types
analysis_path = graph_path.parent / ".graphify_analysis.json"
marker_path = graph_path.parent / ".graphify_semantic_marker"
analysis = {}
if analysis_path.is_file():
    try:
        analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
    except Exception:
        analysis = {}
node_communities = sum(1 for node in nodes if isinstance(node, dict) and node.get("community") is not None)
analysis_communities = analysis.get("communities", {}) if isinstance(analysis, dict) else {}

if not isinstance(nodes, list) or not nodes:
    print("graph has no nodes", file=sys.stderr)
    raise SystemExit(1)
if requires_edges and (not isinstance(edges, list) or not edges):
    print("scope requires graph traversal but graph has no edges", file=sys.stderr)
    raise SystemExit(1)
if scope_path and not marker_path.is_file():
    print("scope extraction lacks semantic marker; LLM-backed extraction is not proven", file=sys.stderr)
    raise SystemExit(1)
if requires_cluster and not node_communities and not analysis_communities:
    print("cluster-required scope lacks communities", file=sys.stderr)
    raise SystemExit(2)
print(json.dumps({
    "nodes": len(nodes),
    "edges": len(edges) if isinstance(edges, list) else 0,
    "node_communities": node_communities,
    "analysis_communities": len(analysis_communities) if isinstance(analysis_communities, dict) else 0,
}))
PY
}

set +e
validation_output="$(validate_graph 2>&1)"
validation_status=$?
set -e

if [ "$validation_status" -eq 2 ] && [ "${GRAPHIFY_CLUSTER_WHEN:-cross_module_only}" != "never" ]; then
    cluster_raw="${TMPDIR}/graphify-${log_slug}.cluster.raw.log"
    set +e
    "${GRAPHIFY_CLI}" cluster-only "${OUTPUT_DIR}" --graph "$graph_path" --backend "${GRAPHIFY_BACKEND}" --model "${GRAPHIFY_MODEL}" >"$cluster_raw" 2>&1
    cluster_status=$?
    set -e
    "${HARNESS_ROOT}/.venv/bin/python" - "$cluster_raw" "$log_path" <<'PY'
import os
import sys
from pathlib import Path

raw = Path(sys.argv[1])
dest = Path(sys.argv[2])
text = raw.read_text(encoding="utf-8", errors="replace") if raw.exists() else ""
for key in ("VULNOPS_GRAPHIFY_API_KEY", "ON_PREM_API_KEY", "OPENAI_API_KEY", "OLLAMA_API_KEY"):
    value = os.environ.get(key, "")
    if value:
        text = text.replace(value, "<redacted>")
with dest.open("a", encoding="utf-8") as fh:
    fh.write("\n[graphify cluster-only]\n")
    fh.write(text)
try:
    raw.unlink()
except FileNotFoundError:
    pass
PY
    if [ "$cluster_status" -ne 0 ]; then
        echo "[graphify] cluster-only failed for scoped extraction; see sanitized log: ${log_path}" >&2
        exit "$cluster_status"
    fi
    set +e
    validation_output="$(validate_graph 2>&1)"
    validation_status=$?
    set -e
fi

if [ "$validation_status" -ne 0 ]; then
    echo "[graphify] scoped extraction failed quality checks: ${validation_output}" >&2
    echo "[graphify] see sanitized log: ${log_path}" >&2
    exit "$validation_status"
fi

if [ -n "$SCOPE_FILE" ]; then
    echo "$validation_output" >"${OUTPUT_DIR}/graphify-quality.json"
fi

echo "[graphify] LLM-backed extraction complete: ${graph_path}"
